# Generated by Django 4.2.1 on 2024-01-16 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('ci', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone_1', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_2', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade_residencia_sede', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data de leitura')),
                ('relogio_1', models.IntegerField(verbose_name='valor do relógio 1')),
                ('relogio_2', models.IntegerField(verbose_name='valor do relógio 2')),
                ('relogio_3', models.IntegerField(verbose_name='valor do relógio 3')),
                ('valor_kwh', models.FloatField(blank=True, null=True, verbose_name='valor do kWh')),
                ('valor_conta', models.FloatField(blank=True, null=True, verbose_name='valor da conta')),
            ],
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=200)),
                ('cpf', models.TextField(blank=True, max_length=20, null=True)),
                ('residencia', models.TextField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.TextField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, max_length=100, null=True)),
                ('telefone', models.TextField(blank=True, max_length=100, null=True)),
                ('email', models.TextField(blank=True, max_length=200, null=True)),
                ('nacionalidade', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cliente')),
            ],
            options={
                'ordering': ['cliente'],
            },
        ),
    ]
