# Generated by Django 4.2.1 on 2024-02-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
