# Generated by Django 4.2.1 on 2024-02-04 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_contrato_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('dia', models.IntegerField(blank=True, null=True)),
                ('cliente_nome', models.CharField(max_length=200)),
                ('cliente_cpf_cnpj', models.CharField(blank=True, max_length=200, null=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel')),
            ],
        ),
    ]
