# Generated by Django 4.2.1 on 2024-02-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='cliente_nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
