# Generated by Django 4.2.1 on 2024-04-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_rename_energiadescricao_energialabels'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='elfsm_inscricao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='elfsm_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elfsm_titular', to='imoveis.locador'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='iptu_inscricao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='iptu_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iptu_titular', to='imoveis.locador'),
        ),
    ]
