# Generated by Django 4.2.1 on 2024-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_elfsm_inscricao_imovel_elfsm_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locador',
            name='principal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
