# Generated by Django 4.2.1 on 2024-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_locador_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locador',
            name='principal',
            field=models.BooleanField(blank=True, default='false', null=True),
        ),
    ]
