# Generated by Django 4.2.1 on 2023-05-10 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateTimeField()),
                ('ci', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=200)),
                ('telefone_1', models.CharField(max_length=100)),
                ('telefone_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('local', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('observacao', models.CharField(max_length=250)),
                ('dia', models.IntegerField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.cliente')),
            ],
        ),
    ]
