# Generated by Django 4.2.1 on 2023-05-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_cliente_data_nascimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data de leitura')),
                ('relogio_1', models.FloatField(verbose_name='valor do relógio 1')),
                ('relogio_2', models.FloatField(verbose_name='valor do relógio 2')),
                ('relogio_3', models.FloatField(verbose_name='valor do relógio 3')),
                ('valor_kwh', models.FloatField(blank=True, null=True, verbose_name='valor do kWh')),
                ('valor_conta', models.FloatField(blank=True, null=True, verbose_name='valor da conta')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['cliente']},
        ),
    ]
